### ISSUE TITLE
Tab-icon missing

### ISSUE THREAD

**Issue by DrillSergeant** [neos/neos-googleanalytics#47]
On my installations: Neos 3.3.12 / UI 1.1.2 the icon of the analytics-tab is missing: 
![image](https://user-images.githubusercontent.com/883552/42160165-81474f66-7df6-11e8-9d4a-339a6ee8a8cd.png)

It is working when I remove the secon icon specified in Settings/NodeTypes.yaml with this setting:
```
'Neos.GoogleAnalytics:StatsTabMixin':
  ui:
    inspector:
      tabs:
        stats:
          icon: 'icon-line-chart'
```

**Comment by DrillSergeant** [comment]
Same problem with the module icon. I my project I fixed it with:
```
Neos:
  Neos:
    modules:
      administration:
        submodules:
          googleAnalytics:
            icon: 'icon-line-chart'
```
