### ISSUE TITLE
setting a default profileId for all sites

### ISSUE THREAD

**Issue by paavo** [neos/neos-googleanalytics#84]
We use [neos-googleanalytics](https://github.com/neos/neos-googleanalytics) in a multisite environment where all sites sharing the same Analytics-Profile. 

It's possible to set a default Analytics-ID but not a profileId in `Neos.GoogleAnalytics.default` 😢  

```
Neos:
  GoogleAnalytics:
    default:
      analytics:
        # this works well
        id: G-XXXXXXX
      # this is missing  
      profileId: 123456789
```
